max_width                           = 120
chain_width                         = 80
fn_call_width                       = 80
attr_fn_like_width                  = 80
short_array_element_width_threshold = 10
single_line_if_else_max_width       = 60
single_line_let_else_max_width      = 60
struct_lit_width                    = 30
struct_variant_width                = 40
use_small_heuristics                = "Default"

fn_params_layout           = "Vertical"
match_arm_leading_pipes    = "Always"
match_block_trailing_comma = true
merge_derives              = true
remove_nested_parens       = true
reorder_imports            = true
reorder_modules            = true
use_field_init_shorthand   = true
use_try_shorthand          = true
